php-parallel-lint/PHP-Parallel-Lint

- parallel-lint
Fixing issue with autoloader when executing from outside the source directory: https://github.com/php-parallel-lint/PHP-Parallel-Lint/issues/1
> Fix vendor location

- .travis.yml
Travis has removed support for `sudo: false`. See: https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration
> Travis: remove sudo

- .travis.yml
Adding a build against `nightly` (PHP 8) which, for now, is allowed to fail.
At this time, there is one unit test which fails `ParallelLint.lint.phpt method=testDeprecated`. This will need to be investigated over time. No urgency yet as it may be related to the Nette testing framework dependency and also PHP 8 is still in flux.
> Travis: test against nightly (= PHP 8)

- tests/Settings.parseArguments.phpt
The `testNoProgress()` test was not testing the `showProgress` property.
This is the same PR as previously pulled in PR JakubOnderka/PHP-Parallel-Lint#150
> Tests/Settings.parseArguments: fix incorrect unit test

- .gitattributes
- .gitignore
- .travis.yml
- composer.json
- phpcs.xml.dist
- tests/Manager.run.phpt
This is the same PR as previously pulled in PR JakubOnderka/PHP-Parallel-Lint#146
The current version is `3.5.4` released end of January 2020 and - aside from lots of bug fixes -, it includes compatibility with PHP 7.4.
See: https://github.com/squizlabs/php_codesniffer/releases
The results of PHPCS run will be no different across PHP versions as all sniffs are unit tested against all supported PHP versions, so it is unnecessary to run it against every PHP version, just run it once per build.
I've chosen to run it against PHP 7.4 as that's the fastest PHP version.
* Rename the ruleset to one which PHPCS will recognize automatically.
This means you no longer need to pass the `--standard` on the command-line.
* Use the `dist` extension to allow for devs to overload the ruleset file locally …
> CS: Various phpcs tweaks

- src/Manager.php
- tests/Manager.run.phpt
- tests/Settings.parseArguments.phpt
- tests/examples/example-06/example.php
- tests/examples/example-06/example.php-dist
- tests/examples/example-06/example.php.dist
Implementation of feature request https://github.com/JakubOnderka/PHP-Parallel-Lint/issues/115.
The user can now pass longer, multi-part extensions on the command-line and they will be respected.
Example:
`-e php,php.dist`
Fixes https://github.com/JakubOnderka/PHP-Parallel-Lint/issues/115
This is the same PR as previously pulled in PR JakubOnderka/PHP-Parallel-Lint#151
> Allow for multi-part file extensions to be passed using -e

- .travis.yml
- appveyor.yml
- composer.json
I checked out the project and it wasn't clear to me how to run the tests (as its not using phpunit). After searching around I found two variations of how to run the tests.
Adding a `scripts` entry to composer provides a single definition on how to run the tests, usable for every one; also locally:
```
$ composer tests
> tester -p php tests
_____ ___  ___ _____ ___  ___
|_   _/ __)( __/_   _/ __)| _ )
|_| \___ /___) |_| \___ |_|_\  v2.3.2
Note: No php.ini is used.
PHP 7.4.7 (cli) | php -n | 8 threads
.........................
OK (25 tests, 1.4 seconds)
```
After that I adapted the existing ones to use the one from composer.
Thanks!
> Provide one true way to run the test suite

- README.md
- doc/syntax-error-callback.md
- src/Application.php
- src/Contracts/SyntaxErrorCallback.php
- src/Manager.php
- src/ParallelLint.php
- src/Settings.php
- src/exceptions.php
- tests/Settings.parseArguments.phpt
Look at this please, this is the first shot about this improvement. Let's discuss it
Closes #24
> Add Syntax Error callback

- src/Process/PhpProcess.php
Ignoring PHP startup errors completely for any PHP processes started from within the application.
Fixes #33
> Ignore PHP startup errors

- .travis.yml
- tests/ParallelLint.lint.phpt
PHP 8.0 has been branched off two months ago, so `nightly` is now PHP 8.1 and in the mean time PHP 8.0 was released last week.
As of today, there is a PHP 8.0 image available on Travis.
This PR adds a new build against PHP 8.0 to the matrix and, as PHP 8.0 has been released, that build is not allowed to fail.
I previously pointed out in #5 that this test was failing, but clearly no action has been taken on that in the mean time. Either way, fixing this now.
This test is expected to throw a deprecation warning for the PHP4-style class constructor (method named the same as the class).
In PHP 8, the deprecation warning is no longer thrown and PHP4-style constructor method are now treated as _normal_ methods.
This fixes the test to have the correct expectations.
> Travis: add build against PHP 8.0 and fix failing test

- src/ParallelLint.php
Fix linter crashing with Xdebug 3 on without listening client - more detailed description in linked issue.
Fixes #47
> Determine skip lint process failure by status code instead of stderr content

- README.md
Make the text more fluent, include the rest of the forking history, include bit about output types, and remove negative emotions from the readme.
> Improve wording in the readme

- .github/workflows/release.yml
- .github/workflows/test.yml
- box.json
Depends on #45, test results are available at [roelofr:#1](https://github.com/roelofr/php-parallel-lint/pull/1), which merge into that master branch.
I'm still seeing errors on this branch, very wierd ones at that:
```
Fatal error: Interface 'JsonSerializable' not found in /home/runner/work/php-parallel-lint/php-parallel-lint/src/Error.php on line 4
```
I don't know why, but the Json class seems unavailable, although the json extension is enabled. 
On PHP 8.0 I even saw `Fatal error: Uncaught Error: Call to undefined function token_get_all()`, which is a built-in and should always work.
Some wierd stuff going on here... :thinking: 
Will close #44.
> GitHub Actions for testing, and automatic phar creation

- CHANGELOG.md
See the guide: https://keepachangelog.com/en/1.0.0/
> Add missing reflinks to changelog

- CHANGELOG.md
See discussion at https://github.com/php-parallel-lint/PHP-Parallel-Lint/pull/57
> Reformat changelog to use reflinks in changelog entries

- README.md
- src/Application.php
- src/Manager.php
- src/Output.php
- src/Settings.php
- tests/Output.phpt
- tests/Settings.parseArguments.phpt
Hi, we use this linter in our PHP projects. We have our repositories in GitLab and use the CI pipeline there. When we run the CI pipeline, we run QA tools. When the pipeline is executed, we want GitLab to load the errors from a json file and display them in the merge request. This should make it easier to see which bugs have been added and which have been fixed.
For this we use the [Code Quality](https://docs.gitlab.com/ee/user/project/merge_requests/code_quality.html#implementing-a-custom-tool) widget. This requires creating a Json file that implements a subset of the code-climate specification. 
With this merge request I suggest that this linter supports this format so that not every CI pipeline has to use a converter.
We also use PHPStan, they support this …
> Extend by the Code Climate output format

- composer.json
- src/Error.php
- src/Manager.php
- src/Result.php
- src/exceptions.php
As of PHP 8.1, PHP adds return type declarations to the PHP native functions.
For the `JsonSerializable::jsonSerialize()` interface method, the new signature is:
```php
function jsonSerialize(): mixed {}
```
As this libary still supports PHP 5.3, it is not possible to add this return type as:
1. Return types weren't available until PHP 7.0 and
2. the `mixed` return type only became available in PHP 8.0.
For libraries supporting PHP 7.0+, it would have been possible to fix this by adding an `array` return type (higher specificity).
For libraries still supporting PHP < 7.0, there are two choices:
1. Either decouple from the `JsonSerialize` interface.
2. Or use a PHP 8.1 attribute to silence the deprecation notice.
As prior to PHP 8.0, attributes are ignored as if they were comments, it is …
> PHP 8.1: silence the deprecation notices about missing return types

- parallel-lint
This prevents the autoload finder from attempting to load the Composer `autoload.php` file of the project under scan when Parallel Lint is being run from a Phar file.
Fixes #61
> Bug fix: make Phar file run independently of project under scan

- composer.json
- tests/php5.3-5.5.ini
I still can't fathom why the tests were previously passing and are failing now. I know they were running fine before as I checked the logs on multiple occasions.
I've now [unearthed the documentation from Nette Tester 1.x](https://web.archive.org/web/20170602082733/https://tester.nette.org/#toc-how-the-tester-runs) which what's used to run the tests on PHP 5.3-5.5.
The docs state:
> The Tester runs PHP processes with `-n` option, so without `php.ini`. More details in the [Own php.ini chapter](https://web.archive.org/web/20170602082733/https://tester.nette.org/#toc-own-php-ini).
... which in a way is similar to the problem we previously ran into for Nette Tester 2.x, which is why the `-C` (= Use system-wide `php.ini`) option is used there. Also see …
> GH Actions: fix failing tests on PHP 5.3-5.5

- .github/workflows/release.yml
- .github/workflows/test.yml
- box.json
Box 2 is no longer maintained and will not be made compatible with more recent PHP versions.
Refs:
* https://github.com/box-project/box/blob/master/UPGRADE.md#from-27-to-30
* https://github.com/box-project/box/blob/master/doc/configuration.md
For the time being, until box-project/box#567 has been fixed:
1. Disable the addition of the requirement checker from Box as the version included in the last release of Box is not compatible with PHP 8.1.
2. Change the PHP version used to generate the Phar to PHP 8.0 to get round the problem the PHP compactor has with attributes.
Note: the generated Phar file should still be compatible with all supported PHP versions.
Fixes #69
Closes #39 
Closes #36
@grogy A release with a Phar generated after this fix has been merged would be appreciated as anyone …
> [Hotfix] Fix Phar building

- README.md
As the Phar is now published with each release (and on each action run), there is no need to include build instruction in the README anymore.
Also, the instructions as they were, were outdated after #70
> README: update info about PHAR

- .github/workflows/release.yml
- .github/workflows/test.yml
Follow-up on PR #65, which turned set `error_reporting` to `E_ALL` and turned `display_errors` on in the Test workflow.
Only just now noticed that I missed doing the same in the Release workflow.
This also changes the setting for `error_reporting` to `-1` as `E_ALL` does not contain **all** errors across PHP versions, while `-1` will show them, independently of the PHP version.
Also turning on assertions, just in case they are used under the hood in the test framework.
No need for the `experimental` key, we can just refer directly to the `matrix.php` version in the `continue-on-error` condition.
Just in case someone would push a tag up to their own fork.
Previously, in Travis, when the same branch was pushed again and the "Auto cancellation" option on the "Settings" page had been turned …
> GH Actions: various improvements to the workflows

- src/Output.php
- tests/Output.phpt
> Use HTML-escaped messages in CheckstyleOutput

- README.md
By default the `.git` directory will also be scanned forPHP files and as it often contains a lot of directories, this can really slow down the run time for the linting.
By adding an exclude for the `.git` directory in the Symfony example, this will hopefully help people realize that excluding the `.git` directory is a good idea.
To be honest, I never realized this was possible until I looked at the code in more detail, so I have a feeling that this feature is barely known.
This feature has been in the codebase since 2014 (b0b05d2), so let's document this option to raise awareness
> README: improve documentation

- .github/workflows/release.yml
PR #51 restored PHP 5.3 support, but the release workflow did not test against PHP 5.3 yet.
> GH Actions: PHP 5.3 was missing from release workflow

- .github/workflows/release.yml
- .github/workflows/test.yml
The action used to install Composer packages and handle the caching has released a new major (and some follow-up patch releases), which means, the action reference needs to be updated to benefit from it.
Includes adding `--no-interaction` to one "plain" Composer command to potentially prevent CI hanging if, for whatever reason, interaction would be needed in the future.
Refs:
* https://github.com/ramsey/composer-install/releases/tag/2.0.0
* https://github.com/ramsey/composer-install/releases/tag/2.0.1
* https://github.com/ramsey/composer-install/releases/tag/2.0.2
> GH Actions: version update for `ramsey/composer-install`

- .gitattributes
The `.github` folder was listed twice.
Includes:
* Sorting the entries by files first, then directories.
* Improving readability of the list.
> .gitignore: remove duplicate entry

- composer.json
As suggested in JakubOnderka/PHP-Parallel-Lint#140
Props @mfn
> Composer: differentiate between dev and no-dev files for autoloading

- README.md
- src/Application.php
- src/Settings.php
This commit syncs the three lists of the supported options:
* The processing of received arguments in the `Application` class.
* The CLI help in the `Settings` class.
* The options shown in the README.
I have verified that:
* The options in all three lists are now in the same order to make future maintenance more straight-forward.
Includes having all functional short options at the top of the lists.
* All options are now shown in the help and the README.
* The descriptions in the help and in the README are complete and largely the same (minus the "further reading" links shown in the README).
Includes:
* Fixing a typo in the help `-asp` vs `--asp`.
* Line length management for the CLI help.
* Minor grammatical improvement.
Fixes #81
> Docs: show all options in help and README

- CHANGELOG.md
- src/Application.php
This updates the changelog with the latest changes to allow for releasing version 1.3.2.
> Release version 1.3.2

- CHANGELOG.md
- composer.json
- src/ErrorFormatter.php
- src/Output.php
PHP Console Highlighter 1.0.0 has just been released.
This PR adds cross-version support for both PHP Console Highlighter < 1.0.0 and 1.0.0+ to PHP Parallel Lint, which allows people to update the Highlighter dependency to the latest version.
Includes changelog entry to allow this PR to still be included in the 1.3.2 release.
Ref: https://github.com/php-parallel-lint/PHP-Console-Highlighter/releases/tag/v1.0.0
> ErrorFormatter: support PHP Console Highlighter 1.0.0

- src/ErrorFormatter.php
This small tweak makes the display of the error message independent of the code snippet implementation and will ensure that the actual error message is always displayed on the next line after the code snippet.
Fixes #93
> ErrorFormatter: fix error msg on last line of code snippet

- parallel-lint
As reported in #62, the "version check" for PHP < 5.3 in the application bootstrap did not work as the code in file would cause a parse error when run on PHP < 5.3.
By putting the class name, which contains PHP 5.3 namespace separator tokens, as a variable and then dynamically calling the class, the parse error on PHP < 5.3 is prevented and the version check at the top of the file can work as expected.
Fixes #62
**_Note_**: this is not something which can really be unit tested as this concerns the application bootstrap file. An integration test would be an option, but then, this integration test would need to be run against PHP 5.2 (or lower) in a workflow.
Adding a setup for this is outside the scope of this PR.
Previously, the PHP version check run at the start of the script would …
> Application bootstrap: fix version check

- tests/Settings.parseArguments.phpt
The `SettingsParseArgumentsTest::testMoreArguments()` method was assigning to a non-existent property in the `Settings` class.
The actual property is called `$showDeprecated` and the assertion was referring to the property correctly.
> SettingsParseArgumentsTest: fix bug in test

- src/Application.php
- src/Blame.php
- src/Errors/ParallelLintError.php
- src/Exceptions/ParallelLintException.php
- src/Iterators/ArrayIterator.php
- src/Iterators/RecursiveDirectoryFilterIterator.php
- src/Manager.php
- src/Outputs/GitLabOutput.php
- src/Outputs/TextOutputColored.php
- src/ParallelLint.php
- src/Process/GitBlameProcess.php
- src/Process/LintProcess.php
- src/Result.php
- tests/Manager.run.phpt
- tests/Output.phpt
- tests/ParallelLint.lint.phpt
- tests/Settings.parseArguments.phpt
- tests/SkipLintProcess.phpt
- tests/SyntaxError.normalizeMessage.phpt
Iterate on consistent coding styles (not checked via the ruleset)
> CS/QA: always import all used classes

- composer.json
- phpcs.xml.dist
- tests/ManagerRunTest.php
- tests/OutputTest.php
- tests/ParallelLintLintTest.php
- tests/SettingsParseArgumentsTest.php
- tests/SkipLintProcessTest.php
- tests/SyntaxErrorNormalizeMessageTest.php
Includes:
* Renaming the files to reflect the name of the class therein and to use the `php` instead of `phpt` file extension.
* Updating the `autoload-dev` directive in the `composer.json` file.
* Updating the exclusions in the PHPCS config.
Note: using PSR-4 compliant `*Test,php` filenames will (temporarily) silently break the running of the tests for PHP 5.3-5.5 as Nette Tester 1.x can't find the tests anymore.
We can ignore this for now as this will be fixed in one of the next PRs where the tests will switch over to the PHPUnit testing framework.
> CS/QA: Tests: add PSR-4 compliant namespace declarations

- .github/workflows/release.yml
- .github/workflows/test.yml
A number of predefined actions have had major release, which warrant an update to the workflow(s).
These updates don't actually contain any changed functionality, they are mostly just a change of the Node version used by the action itself (from Node 14 to Node 16).
Refs:
* https://github.com/actions/checkout/releases
* https://github.com/actions/download-artifact/releases
* https://github.com/actions/upload-artifact/releases
> GH Actions: version update for various predefined actions

- src/Errors/ParallelLintError.php
- tests/Unit/Errors/ParallelLintErrorTest.php
This safeguards and documents the current behaviour of the methods in the class.
Includes ignoring one line in the class for code coverage as the return of `getcwd()` cannot be mocked without adding additional test frameworks into the mix.
> Tests: add dedicated test class for the ParallelLintError class

- tests/Unit/SettingsParseArgumentsTest.php
Refactor the tests in the `SettingsParseArgumentsTest` class to use a data provider, which allow for adding more tests in a straight forward manner.
Includes expanding the actual tested settings values (values of the properties in the `Settings` class).
Previously, there were two tests which tested a range of property values, though still not all and multiple other tests which only verified one particular property value.
With the adjusted setup, all property values, except for the `phpExecutable`, will be tested for each and every test case.
Note: this is a 1-on-1 refactor of the test with all existing test cases still being tested but no other changes.
... to make sure all possible arguments handled by the `Settings::parseArguments()` method are covered by tests.
> SettingsParseArgumentsTest: improve the tests

- tests/Unit/SettingsAddPathsTest.php
... containing perfunctory tests for the `Settings::addPaths()` method.
> Tests: new `SettingsAddPathsTest`

- .github/workflows/release.yml
- .github/workflows/test.yml
During builds, the PHAR file is generated and uploaded as an artefact to be used during the test job.
Along the same lines, the PHAR file is generated via a GH Actions workflow when a new version has been tagged and uploaded to the "Release".
Composer 2.3 has been released last week, which has a minimum PHP version of PHP 7.2 and the autoload files generated with Composer 2.3 are no longer compatible with PHP < 7.0.
Composer 2.2 (with a minimum PHP version of PHP 5.3) is now a LTS (long term service) release and will receive essential bug fixes.
The `setup-php` action runner will automatically install the appropriate version of Composer depending on the PHP version requested - Composer 2.2 for PHP < 7.2 and Composer 2.3+ for PHP 7.2+.
For the PHAR file, which is being generated on PHP 8.0 …
> 🔥 Hot fix: Fix PHAR not being compatible with PHP < 7.0 / Composer 2.3

- .github/workflows/release.yml
- .github/workflows/test.yml
Same as PR #116, but now for `develop`.
---
During builds, the PHAR file is generated and uploaded as an artefact to be used during the test job.
Along the same lines, the PHAR file is generated via a GH Actions workflow when a new version has been tagged and uploaded to the "Release".
Composer 2.3 has been released last week, which has a minimum PHP version of PHP 7.2 and the autoload files generated with Composer 2.3 are no longer compatible with PHP < 7.0.
Composer 2.2 (with a minimum PHP version of PHP 5.3) is now a LTS (long term service) release and will receive essential bug fixes.
The `setup-php` action runner will automatically install the appropriate version of Composer depending on the PHP version requested - Composer 2.2 for PHP < 7.2 and Composer 2.3+ for PHP 7.2+.
For the …
> Fix PHAR not being compatible with PHP < 7.0 / Composer 2.3

- src/Errors/SyntaxError.php
- tests/Unit/Errors/SyntaxErrorGetLineTest.php
This safeguards and documents the current behaviour of the method.
Includes removing redundant conditional in the original method.
> Tests: add dedicated test for the `SyntaxError::getLine()` method

- src/Errors/SyntaxError.php
- tests/Unit/Errors/SyntaxErrorTranslateTokensTest.php
This safeguards and documents the current behaviour of the method.
Generally speaking, the `$translate` parameter for the `SyntaxError::getNormalizedMessage()` method should only be passed as `true` when on a PHP version which doesn't do the PHP native token translation yet.
However, in edge cases, it could be possible that tokens could be double "translated", both by PHP itself as well as by the `SyntaxError::translateTokens()` method.
This minor fix prevents this by not matching token names when surrounded by parentheses.
Includes additional unit tests.
> Tests: add dedicated test for the SyntaxError::translateTokens() method + edge case bug fix

- src/Errors/SyntaxError.php
- tests/Unit/Errors/SyntaxErrorGetNormalizeMessageTest.php
Refactor the tests in the `SyntaxErrorGetNormalizeMessageTest` class to use data providers, which allow for adding more tests in a straight forward manner.
Note: this is a 1-on-1 refactor of the test with all existing test cases still being tested but no other changes.
If a file name would contain the delimiter used in the replacement regex, it would cause a PHP error like `preg_replace(): Unknown modifier 'f'`.
Fixed by telling `preg_quote()` explicitly which delimiter is being used.
Includes unit test.
Ref: https://www.php.net/manual/en/function.preg-quote.php
In certain cases, PHP puts the full file name in the error message. In those cases the "in filename.php on line .." trailing part of the error message did not get stripped off.
Also, in some cases, when Windows slashes are used in …
> SyntaxError::getNormalizedMessage(): improve tests + 2 bug fixes

- .github/workflows/release.yml
- .github/workflows/test.yml
The box project has released Box 4.0.0 (and 4.0.1).
Most notable changes:
* New minimum PHP version of PHP 8.1.
* The sodium extension has become a requirement.
* The requirements checker now has a minimum PHP version of PHP 7.2.4.
We already disabled the requirements checker previously due to PHP 8.1 incompatibilities (PR #70), I've now added a comment to document not to turn it on again as that would make the Parallel Lint PHAR incompatible with PHP < 7.2.
Refs: https://github.com/box-project/box/releases/tag/4.0.0
----
Note: I'm pulling this PR to `master` to ensure the PHARs for the `1.x` branch will be PHP cross-version compatible.
I will open a separate PR for the same for the `develop` branch.
> GH Actions: updates for box 4.x (`master`)

- .github/workflows/release.yml
- .github/workflows/test.yml
Sister-PR to #121.
The box project has released Box 4.0.0 (and 4.0.1).
Most notable changes:
* New minimum PHP version of PHP 8.1.
* The sodium extension has become a requirement.
* The requirements checker now has a minimum PHP version of PHP 7.2.4.
We already disabled the requirements checker previously due to PHP 8.1 incompatibilities (PR #70), I've now added a comment to document not to turn it on again as that would make the Parallel Lint PHAR incompatible with PHP < 7.2.
Refs: https://github.com/box-project/box/releases/tag/4.0.0
> GH Actions: updates for box 4.x (`develop`)

- .github/workflows/release.yml
- .github/workflows/test.yml
Looks like the box project has moved organisations, so let's update the URL used to download the PHAR.
As GitHub will automatically redirect moved URLs anyway, I'm only pulling this to the `develop` branch.
> GH Actions: fix download URL for box

- .github/workflows/test.yml
If there is a ruleset error, the `cs2pr` action doesn't receive an `xml` report and exits with a `0` error code, even though the PHPCS run failed (though not on CS errors, but on a ruleset error).
This changes the GH Actions workflow to allow for that situation and still fail the build in that case.
> GH Actions: harden the workflow against PHPCS ruleset errors

- .github/workflows/release.yml
- .github/workflows/test.yml
PHP 8.2 has been released today :tada: and the `setup-php` action has announced support for PHP 8.3, so adding PHP 8.3 to the matrix and no longer allowing PHP 8.2 to fail the build.
Builds against PHP 8.3 are still allowed to fail for now.
Includes minor tweak setting PHP to `latest` for tasks where the PHP version isn't that relevant.
> GH Actions: update PHP versions in workflows

- .github/workflows/release.yml
- .github/workflows/test.yml
Caches used in GH Actions do not get updated, they can only be replaced by a different cache with a different cache key.
Now the predefined Composer install action this repo is using already creates a pretty comprehensive cache key:
> `ramsey/composer-install` will auto-generate a cache key which is composed of
the following elements:
> * The OS image name, like `ubuntu-latest`.
> * The exact PHP version, like `8.1.11`.
> * The options passed via `composer-options`.
> * The dependency version setting as per `dependency-versions`.
> * The working directory as per `working-directory`.
> * A hash of the `composer.json` and/or `composer.lock` files.
This means that aside from other factors, the cache will always be busted when changes are made to the (committed) `composer.json` or the …
> GH Actions: bust the cache semi-regularly

- .github/workflows/release.yml
- .github/workflows/test.yml
The recent build failure was due to the `setup-php` action running into a rate limit and not downloading the required version of Composer (`2.2`), which meant that the PHAR ended up being build with Composer 2.4.
The `setup-php` action runner defaults to _showing_ these type errors in the logs, but not stopping the workflow run.
For the creation of the binary it is really important that the correct Composer version is used as otherwise the PHAR file won't be compatible with PHP 5.3 - 5.5.
So, specifically for those jobs, I'm adding the `fail-fast` option to `setup-php` to fail the build if the action runner ran into any errors.
Ref: https://github.com/shivammathur/setup-php#fail-fast-optional
> GH Actions: use `fail-fast` with setup-php when creating the binaries

- tests/Manager.run.phpt
- tests/Output.phpt
- tests/ParallelLint.lint.phpt
- tests/Settings.parseArguments.phpt
- tests/SkipLintProcess.phpt
- tests/SyntaxError.normalizeMessage.phpt
I changed description ~15min after creating a PR. PR solve 2 issues:
**1. issue with Nette Tester**
Is necesary setup library for PHP unit tests.
Library Nette Tester is used of 1.x version (on master branch). 
[An error](https://github.com/nette/tester/pull/442) in Nette Tester is the reason for failing unit tests.
This PR will not be pushed to `develop` branch. It used PHPUnit library.
**2. issue with incorrect property name**
Second commit resolve issue with missing property. Mistake comes from https://github.com/JakubOnderka/PHP-Parallel-Lint/pull/94/files#diff-0f72a4d5de7cb5a661be1a8151dc9a3c0c38d7dd00b005f0c1ce39082021872aR61 that is a typo.
> Fix unit tests in master branch - unit tests library issue

- src/Outputs/TextOutput.php
Left pad with whitespace so that the 100% line doesn't pop out of alignment.
Before:
```
............................................................  60/337 (17 %)
............................................................ 120/337 (35 %)
............................................................ 180/337 (53 %)
............................................................ 240/337 (71 %)
............................................................ 300/337 (89 %)
.....................................                        337/337 (100 %)
```
After:
```
............................................................  60/337 ( 17%)
............................................................ 120/337 ( 35%)
............................................................ 180/337 ( 53%) …
```
> Align the percentage output

- .github/workflows/release.yml
- .github/workflows/test.yml
Looks like Box silently dropped support for PHP 8.1. Upgrading the version on which Box is run to 8.2 should fix this. The resulting PHAR files should still work fine on PHP < 8.2.
Ref: https://github.com/box-project/box/releases
Note: this commit will need to be back-ported to the `master` branch to get passing builds there again too.
> GH Actions: update PHP version for PHAR boxing

- src/Manager.php
Fixes all issues that emit deprecation notices on PHP 8.4 for implicit nullable parameter type declarations.
See:
- [RFC](https://wiki.php.net/rfc/deprecate-implicitly-nullable-types)
- [PHP 8.4: Implicitly nullable parameter declarations deprecated](https://php.watch/versions/8.4/implicitly-marking-parameter-type-nullable-deprecated)
> [PHP 8.4] Fixes for implicit nullability deprecation

- tests/Unit/Outputs/OutputTest.php
The `OutputTest::testGitLabOutput()` was being marked as risky for the first test case (no errors) as no assertions were being run.
This commit adds an extra assertion to prevent this, but also to make the test more thorough as the test will now also fail if the number of errors expected versus received does not match.
> OutputTest: fix risky test

- composer.json
As of Composer 2.4, Composer will recommend putting a dependency in `require-dev` over `require` when certain keywords are encountered.
As PHP Parallel Lint should be placed in `require-dev`, this commit adds those keywords to trigger this notification for end-users (when needed).
Closes #134
> Composer: add keywords

- bin/skip-linting.php
- tests/Unit/ParallelLintLintTest.php
- tests/fixtures/fixture-07/example.php
When linting executable files the first line is not always the php opening tag.
On such occasions we need to skip the shebang line, and read next line.
> Skip shebang sequence if it is the first line

- .github/workflows/release.yml
As things were, the workflow was creating two releases, one in draft and one published, but without a good name/changelog. I noticed this last time there was a release, but never got round to fixing it (and it wasn't urgent as no new release was needed).
As a new release is needed soon, now seemed like a good time to fix this.
The `actions/create-release` action runner has been abandoned and mentions the `softprops/action-gh-release` action runner as a replacement.
This commit now updates the workflow to solely use the `softprops/action-gh-release` action runner and updates the version and configuration to make sure it only creates a draft release, so we can still edit it and add the changelog before publishing.
> GH Actions: fix duplicate release

- .github/workflows/release.yml
- .github/workflows/test.yml
- README.md
- bin/skip-linting.php
- composer.json
- parallel-lint
- src/Error.php
- src/Manager.php
- src/Output.php
- tests/Output.phpt
- tests/ParallelLint.lint.phpt
- tests/examples/example-07/example.php
PHP 8.3 + 8.4 for master branches. It is based from #150
> PHP 8.3 + 8.4 to master branch
